### ISSUE TITLE
상품 데이터 입력

### ISSUE THREAD

**Issue by chhak2021** [Haseonj/Kmarket#11]
- 관리자/상품등록 기능구현이 완료 후 상품데이터 입력하기
- 각 카테고리별 상품 데이터 입력하기
- 각 카테고리별 최소 10개 이상 입력하기(모든 팀원 1명당 3개이상 카테고리 담당)
- 상품 데이터와 이미지는 오픈마켓(Gmarket) 참고하기

**Comment by Haseonj** [comment]
2022/12/27 상품데이터 입력 완료
